### ISSUE TITLE
Ensure that every issue is assigned to a project

### ISSUE THREAD

**Issue by vojtechjelinek** [oppia/oppiabot#157]
Ensure that every issue is assigned to a project. This should be done with two things:

1. Oppiabot comments on new issues that they need to be assigned to some project
2. Periodic job will comment on issues that are not yet assigned to some project

**Comment by vojtechjelinek** [comment]
@anandwana001 Hi, did you have time to look into this?

**Comment by anandwana001** [comment]
Get stuck at the android side. I will schedule a meeting with @jameesjohn or you(@vojtechjelinek) if anyone is available regarding this issue and also just saw the email regarding node.js. If you could help me get started with it and if there is any other issue you want me to work on.

**Comment by jameesjohn** [comment]
Sure, we can schedule a meeting to discuss this.

**Comment by Naman-1234** [comment]
@jameesjohn  and @vojtechjelinek , Sir as anandwana sir has made this issue open for others. I would like to work on this one, Could you assign me please.Thanks.

**Comment by Naman-1234** [comment]
@jameesjohn  Sir Could you help me out a little Please. Actually. I build this approach:
1. First get all open issues.
2. Then see if each one has project one assigned or not.

But the approach failed since I found out that the issue does not have a property of projects. 

Then I thought of dropping first and using project API instead. But in github api docs,it is mentioned that it is currently in preview state.
![Screenshot (30)](https://user-images.githubusercontent.com/63748249/112766230-64dc8100-902e-11eb-9e73-02289ead97bd.png)

I tried to put the header as mentioned in the above as mentioned in the above screenshot but it still does not give anything related to issue, So that we can check if it is associated with which issue.

Could you please help me out with the approach I should follow.

**Comment by seanlip** [comment]
Per the new triage process, we are not going to do this with oppiabot. Closing.
