### ISSUE TITLE
Bot is asking @undefined user to add changelog label to the PR

### ISSUE THREAD

**Issue by DubeySandeep** [oppia/oppiabot#201]
OppiaBot is leaving is asking undefined users for adding a changelog label.

`Hi @undefined, @undefined -- could one of you please add the appropriate changelog label to this pull request? Thanks!`

Comment link: https://github.com/oppia/oppia/pull/11957#issuecomment-779131071

**Comment by jameesjohn** [comment]
I've looked into this problem, and I think this happened because GitHub triggered the pull_request.opened event before requesting reviews from the code owners.
This comment https://github.com/oppia/oppia/pull/11957#issuecomment-779131071 came before the notification of requesting code owner reviews. Hence when the bot tried to ask a reviewer to add the appropriate label, it got undefined.

**Comment by jameesjohn** [comment]
In https://github.com/oppia/oppia/pull/11967, GitHub requested the reviews from code owners before triggering the `pull_request.opened` event, then the bot was able to ask the appropriate reviewer to add the changelog label.

So I think the fix for this is to delay the changelog label check by some seconds to carter for any change in order from Github. What do you think @vojtechjelinek?

**Comment by vojtechjelinek** [comment]
@jameesjohn Yep, I'm fine with that, we just need to make sure that no more timeouts occur or that they are properly handled.

**Comment by vojtechjelinek** [comment]
This error still happens.
